# ДЗ Урок 2

In [1]:
import numpy as np

In [2]:
def permutations(n: int) -> int:
    """Число перестановок.
    """
    
    return np.math.factorial(n)

In [3]:
def arrangements(n: int, k: int) -> int:
    """Число размещений.
    """
    
    return np.math.factorial(n) // np.math.factorial(n - k)

In [4]:
def combinations(n: int, k: int) -> int:
    """Число сочетаний.
    """
    
    return np.math.factorial(n) // (np.math.factorial(k) * np.math.factorial(n - k))

In [5]:
def poisson_proba(k: int, lambda_: float) -> float:
    """Формула Пуассона.
    """
    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)

## Задача 1

Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).

Так ка вопросов 5, то значит X может принимать следующие значения: 0, 1, 2, 3, 4, 5

Для $P(x=0)$ это число комбинаций неправильных ответов деленное на число комбинаций в принципе

In [6]:
Px0 = combinations(15, 5) / combinations(20, 5)
Px0

0.19369195046439627

Для $P(x=1)$ это число комбинаций правильных ответов, умножить на комбинации неправильных и делить на в принципе

In [7]:
Px1 = combinations(5, 1) * combinations(15, 4) / combinations(20, 5)
Px1

0.44020897832817335

$P(x=2)$

In [8]:
Px2 = combinations(5, 2) * combinations(15, 3) / combinations(20, 5)
Px2

0.29347265221878227

$P(x=3)$

In [9]:
Px3 = combinations(5, 3) * combinations(15, 2) / combinations(20, 5)
Px3

0.06772445820433437

$P(x=4)$

In [10]:
Px4 = combinations(5, 4) * combinations(15, 1) / combinations(20, 5)
Px4

0.004837461300309598

$P(x=5)$

In [11]:
Px5 = combinations(5, 5) / combinations(20, 5)
Px5

6.449948400412796e-05

In [12]:
x_values = np.arange(0, 6)
print(x_values)

[0 1 2 3 4 5]


In [13]:
x_probabilities = np.array([Px0, Px1, Px2, Px3, Px4, Px5])
print(x_probabilities)

[1.93691950e-01 4.40208978e-01 2.93472652e-01 6.77244582e-02
 4.83746130e-03 6.44994840e-05]


$M(X)$

In [14]:
m = x_values.dot(x_probabilities)

print(m)

1.25


In [15]:
y_values = x_values - m
print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


In [16]:
z_values = y_values ** 2

print(z_values)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


$D(X)$

In [17]:
d = z_values.dot(x_probabilities)

print(d)

0.7401315789473685


## Задача 2

Пользователь получает в среднем 10 писем со спамом на свой почтовый ящик за сутки. Найти число N, такое, что с вероятностью 0.95 пользователь получит не более N писем со спамом за текущий день.

In [18]:
lambda_ = 10

In [19]:
for x in range(20):
    p = sum(poisson_proba(k=i, lambda_=lambda_) for i in range(x))
    print(x, p)

0 0
1 4.5399929762484854e-05
2 0.0004993992273873334
3 0.0027693957155115762
4 0.010336050675925718
5 0.029252688076961072
6 0.06708596287903178
7 0.13014142088248296
8 0.22022064660169893
9 0.33281967875071894
10 0.45792971447185227
11 0.5830397501929856
12 0.6967761463031068
13 0.7915564763948745
14 0.8644644226193111
15 0.9165415270653373
16 0.9512595966960214
17 0.972958390215199
18 0.9857223864029505
19 0.9928134953961458


$N = 15$

## Задача 3

Производятся выстрелы по мишени. Вероятность попадания в мишень при одном выстреле равна 0.01. Сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 6 раз будет совершено попадание?

Подсказка. Здесь предстоит немножко покодить.

$P = 0.9$

$p = 0.01$

$k = 6$

$P(X = k) = C_n^k p^k (1 - p)^{n - k}$

$combinations(n, k) * (p ** k) * ((1 - p) ** (n - k))$

In [20]:
P = 0.9
i = 6
Pn = 0

In [21]:
def bernulli(n: int, k: int, p: float) -> float:
    """Формула Бернулли.
    """
    
    return combinations(n, k) * (p ** k) * ((1 - p) ** (n - k))

In [22]:
while Pn < P:
    n = i
    k = i
    Pn = sum(bernulli(n, k, 0.01) for k in range(6, k))
    i += 1
print(k, Pn)

926 0.9003627121531275


$N = 926$